print("BACKUP INFO - 12EN12 Backend")
print("Archivos del proyecto:")
print("1. calma_engine.py - 1005 lineas - Motor CALMA v2 reglas de conteo")
print("2. calculator.py - 839 lineas - Busqueda, ajuste, sugerencias")
print("3. meal_templates.py - 1244 lineas - 60 plantillas de menu")
print("4. macro_distribution.py - 626 lineas - 16 tablas distribucion")
print("5. server.py - 1568 lineas - API FastAPI con todos los endpoints")
print("Tests: 216 total (50 calma + 41 calculator + 70 templates + 55 distribution)")
print("Todos los tests PASAN")
